language: ruby

rvm:
  - 2.0.0
  - 2.1.4
  - jruby-19mode

branches:
  only:
    - master

notifications:
  email:
    on_success: change
    on_failure: always

install: "bundle --jobs 4"
script: bundle exec rspec
